In [6]:
# ======= Variables =========

# Fill in the variables below and run cell first
# Note: Use forward slashes / instead of backslashes \ in file paths

DATASET_DIR = "../dataset"
OUTPUT_DIR = f"{DATASET_DIR}/original_sheets"

MODEL_TABLE_FILENAME = "model_table.csv"
DIAGNOSIS_DATASET_FILENAME = "diagnosis_dataset.csv"
OUTPUT_MODEL_TABLE_FILENAME = "model_table_feature_engineered.csv"

In [7]:
# Read the model_table and diagnosis_dataset DataFrames

import pandas as pd

model_table_df = pd.read_csv(f"{DATASET_DIR}/{MODEL_TABLE_FILENAME}")
diagnosis_dataset_df = pd.read_csv(f"{DATASET_DIR}/{DIAGNOSIS_DATASET_FILENAME}")

print(f"Model table: rows={model_table_df.shape[0]}, columns={model_table_df.shape[1]}")
print(f"Diagnosis dataset: rows={diagnosis_dataset_df.shape[0]}, columns={diagnosis_dataset_df.shape[1]}")

Model table: rows=4020, columns=9
Diagnosis dataset: rows=4020, columns=4

In [4]:
# Explore unique values for model table
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))
from ml_antiviral_diagnosis import summarize_unique_values

model_table_eda_df = summarize_unique_values(model_table_df)
model_table_eda_df

,column,dtype,unique_count,unique_values
0,PATIENT_ID,int64,4020,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1,TARGET,int64,2,"[0, 1]"
2,DISEASEX_DT,str,77,"[2022-06-11, 2022-06-22, 2022-06-20, 2022-06-3..."
3,PATIENT_AGE,int64,86,"[34, 2, 49, 0, 71, 1, 45, 31, 74, 32, 23, 82, ..."
4,PATIENT_GENDER,str,2,"[M, F]"
5,NUM_CONDITIONS,int64,7,"[0, 2, 1, 3, 4, 6, 5]"
6,PHYSICIAN_TYPE,str,78,"[FAMILY MEDICINE, EMERGENCY MEDICINE, PEDIATRI..."
7,PHYSICIAN_STATE,str,53,"[TX, PA, MS, nan, CA, WV, ME, FL, AL, AR, MD, ..."
8,LOCATION_TYPE,str,28,"[EMERGENCY ROOM - HOSPITAL, OFFICE, INDEPENDEN..."

In [5]:
# Peruse the unique values of a specific column
column_name = "PHYSICIAN_TYPE"
values = model_table_eda_df.loc[
    model_table_eda_df["column"] == column_name, "unique_values"
].iloc[0]
values

['FAMILY MEDICINE',
 'EMERGENCY MEDICINE',
 'PEDIATRICS',
 nan,
 'DIAGNOSTIC RADIOLOGY',
 'NURSE PRACTITIONER',
 'ANATOMIC/CLINICAL PATHOLOGY',
 'PEDIATRIC EMERGENCY MEDICINE (PEDIATRICS)',
 'HOSPITALIST',
 'GENERAL PREVENTIVE MEDICINE',
 'DERMATOPATHOLOGY',
 'FORENSIC PATHOLOGY',
 'CARDIOVASCULAR DISEASE',
 'PHYSICIAN ASSISTANT',
 'INTERNAL MEDICINE',
 'OBSTETRICS & GYNECOLOGY',
 'HEMATOLOGY/ONCOLOGY',
 'SPORTS MEDICINE (FAMILY MEDICINE)',
 'PULMONARY CRITICAL CARE MEDICINE',
 'INTERNAL MEDICINE/PEDIATRICS',
 'INFECTIOUS DISEASE',
 'ANESTHESIOLOGY',
 'MEDICAL GENETICS',
 'ORTHOPEDIC SURGERY',
 'GERIATRIC MEDICINE (FAMILY MEDICINE)',
 'BEHAVIORAL HEALTH & SOCIAL SERVICES',
 'GENERAL PRACTICE',
 'PUBLIC HEALTH & GENERAL PREVENTIVE MEDICINE',
 'PEDIATRIC EMERGENCY MEDICINE',
 'PEDIATRIC RADIOLOGY',
 'PEDIATRIC CARDIOLOGY',
 'GENERAL SURGERY',
 'PHARMACIST',
 'PEDIATRIC HEMATOLOGY/ONCOLOGY',
 'VASCULAR & INTERVENTIONAL RADIOLOGY',
 'HOSPICE & PALLIATIVE MEDICINE',
 'ADOLESCENT MEDICINE (PEDIATRICS)',
 'NOT APPLICABLE',
 'UNSPECIFIED',
 'THORACIC SURGERY',
 'PODIATRIST',
 'SPORTS MEDICINE (PEDIATRICS)',
 'PSYCHIATRY',
 'HEMATOLOGY (PATHOLOGY)',
 'MATERNAL & FETAL MEDICINE',
 'GERIATRIC MEDICINE (INTERNAL MEDICINE)',
 'RADIOLOGY',
 'PHYSICAL THERAPY',
 'GASTROENTEROLOGY',
 'SPORTS MEDICINE (EMERGENCY MEDICINE)',
 'EMERGENCY MEDICAL SERVICES',
 'ANATOMIC PATHOLOGY',
 'OTOLARYNGOLOGY',
 'SELECTIVE PATHOLOGY',
 'ALLERGY & IMMUNOLOGY',
 'PULMONARY DISEASE',
 'NEPHROLOGY',
 'NUCLEAR MEDICINE',
 'ADVANCED REGISTERED NURSE',
 'RADIATION ONCOLOGY',
 'NEUROMUSCULAR MEDICINE (NEUROLOGY)',
 'INTERNAL MEDICINE/EMERGENCY MEDICINE',
 'CLINICAL SOCIAL WORKER',
 'CRITICAL CARE MEDICINE (INTERNAL MEDICINE)',
 'NEURORADIOLOGY',
 'PAIN MEDICINE',
 'ENDOCRINOLOGY, DIABETES & METABOLISM',
 'STUDENT, HEALTH CARE',
 'UROLOGY',
 'INTERNAL MEDICINE/FAMILY MEDICINE',
 'CHILD & ADOLESCENT PSYCHIATRY',
 'CYTOPATHOLOGY',
 'RHEUMATOLOGY',
 'PHYSICAL MEDICINE & REHABILITATION',
 'PAIN MEDICINE (PHYSICAL MEDICINE & REHABILITATION)',
 'NEUROLOGY',
 'SLEEP MEDICINE',
 'BLOOD BANKING/TRANSFUSION MEDICINE']

In [8]:
# Add transaction-based features to the model table
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from ml_antiviral_diagnosis.feature_engineering import add_model_table_transaction_features

feature_engineered_model_table_df = add_model_table_transaction_features(
    model_table_df=model_table_df,
    diagnosis_dataset_df=diagnosis_dataset_df,
 )

print(
    f"Feature-engineered model table: rows={feature_engineered_model_table_df.shape[0]}, "
    f"columns={feature_engineered_model_table_df.shape[1]}"
 )
feature_engineered_model_table_df[["PATIENT_ID", "INSURANCE_TYPE", "CONTRAINDICATIONS"]].head()

Feature-engineered model table: rows=4020, columns=11

   PATIENT_ID INSURANCE_TYPE CONTRAINDICATIONS
0           1     COMMERCIAL       Unspecified
1           2     COMMERCIAL       Unspecified
2           3     COMMERCIAL       Unspecified
3           4     COMMERCIAL       Unspecified
4           5     COMMERCIAL       Unspecified

In [10]:
# Explore unique values for feature_engineered_model_table_df
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))
from ml_antiviral_diagnosis import summarize_unique_values

feature_engineered_model_table_eda_df = summarize_unique_values(feature_engineered_model_table_df)
feature_engineered_model_table_eda_df

,column,dtype,unique_count,unique_values
0,PATIENT_ID,int64,4020,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1,TARGET,int64,2,"[0, 1]"
2,DISEASEX_DT,str,77,"[2022-06-11, 2022-06-22, 2022-06-20, 2022-06-3..."
3,PATIENT_AGE,int64,86,"[34, 2, 49, 0, 71, 1, 45, 31, 74, 32, 23, 82, ..."
4,PATIENT_GENDER,str,2,"[M, F]"
5,NUM_CONDITIONS,int64,7,"[0, 2, 1, 3, 4, 6, 5]"
6,PHYSICIAN_TYPE,str,78,"[FAMILY MEDICINE, EMERGENCY MEDICINE, PEDIATRI..."
7,PHYSICIAN_STATE,str,53,"[TX, PA, MS, nan, CA, WV, ME, FL, AL, AR, MD, ..."
8,LOCATION_TYPE,str,28,"[EMERGENCY ROOM - HOSPITAL, OFFICE, INDEPENDEN..."
9,INSURANCE_TYPE,str,4,"[COMMERCIAL, MEDICARE, UNSPECIFIED, MEDICAID]"
10,CONTRAINDICATIONS,str,4,"[Unspecified, Low, Medium, High]"

In [ ]:
# Save the feature-engineered model table
output_path = f"{DATASET_DIR}/{OUTPUT_MODEL_TABLE_FILENAME}"
feature_engineered_model_table_df.to_csv(output_path, index=False)

print(f"Saved feature-engineered model table to {output_path}")